# Generated by Django 5.2 on 2025-06-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transcript.meetings'),
        ),
    ]
